#!/bin/sh
# postrm script for mysql-utilities

echo "postrm script for mysql-utilities"
for PYVER in $(pyversions -i)
do
	echo "found"$PYVER
	PYDIST=`$PYVER -c "from distutils.sysconfig import get_python_lib; print (get_python_lib())"`
	echo $PYDIST
	MYSQLINIT="/mysql/__init__.py"
	if [ -d $PYDIST"/mysql" ];
	then
		SUBPKGS=`ls --ignore=*.pyc --ignore=*.pyo -m $PYDIST/mysql`
		if [ "$SUBPKGS" = "__init__.py" ];
		then
			rm $PYDIST$MYSQLINIT
			rmdir $PYDIST/mysql/
		fi
	else
		echo "not found /mysql"
	fi
done

PYSHARED="/usr/share/pyshared"
# Try to remove the MySQL top package mysql/
SUBPKGS=`ls --ignore=*.pyc --ignore=*.pyo -m $PYSHARED/mysql`
if [ "$SUBPKGS" = "__init__.py" ];
then
	echo "$PYSHARED/mysql/__init__.py*"
    rm $PYSHARED/mysql/__init__.py*
    # This should not fail, but show error if any
    rmdir $PYSHARED/mysql/
fi

#DEBHELPER#

exit 0
