#!/bin/sh -e

#DEBHELPER#
# postinst script for mysql-utilities

echo "postinst script for mysql-utilities"
PYVERS=`pyversions -i`

echo $PYVERS
for PYVER in $(pyversions -i)
do
	echo "found"
	echo $PYVER
	PYSHARED="/usr/share/pyshared"
	PYDIST=`$PYVER -c "from distutils.sysconfig import get_python_lib; print (get_python_lib(standard_lib=True, plat_specific=True))"`
	echo $PYDIST
	MYSQLINIT="/dist-packages/mysql/__init__.py"
	if [ -d $PYDIST/dist-packages/mysql ];
	then	
		if [ ! -e $PYDIST/dist-packages/mysql/__init__.py ] && [ ! -L $PYDIST/dist-packages/mysql/__init__.py ];
		then
			ls $PYDIST/dist-packages/mysql
			touch $PYDIST$MYSQLINIT
			ls $PYDIST$MYSQLINIT -la
		fi
		
	else
		# we should not reach this point.
		echo "WARNING: $PYDIST/dist-packages/mysql not found, nothing to do."
	fi
done

exit 0
