#!/bin/sh
# postrm script for mysql-utilities

echo "postrm script for mysql-utilities"
for PYVER in $(pyversions -i)
do
	echo "found"$PYVER
	PYDIST=`$PYVER -c "from distutils.sysconfig import get_python_lib; print (get_python_lib(standard_lib=True, plat_specific=True))"`
	echo $PYDIST
	MYSQLINIT="/site-packages/mysql/__init__.py"
	if [ -d $PYDIST"/site-packages/mysql" ];
	then
		SUBPKGS=`ls --ignore=*.pyc --ignore=*.pyo -m $PYDIST/mysql`
		if [ "$SUBPKGS" = "__init__.py" ];
		then
			rm $PYDIST$MYSQLINIT
			rmdir $PYDIST/site-packages/mysql/
		fi
	else
		echo "not found /site-packages/mysql"
	fi
done

#DEBHELPER#

exit 0
