#!/bin/sh
#
# Change User to .py files.
#

MU="/Library/Python/2.7/site-packages/mysql"

chown -R root:wheel "${MU}"
#chmod -R g+w "${MU}"

echo 'permissions changed, postflight finish.'

exit 0
