INSERT INTO util_test.t1 VALUES ("21 Test Basic database example"); 
INSERT INTO util_test.t1 VALUES ("22 Test Basic database example"); 
INSERT INTO util_test.t1 VALUES ("23 Test Basic database example"); 
INSERT INTO util_test.t1 VALUES ("24 Test Basic database example"); 
INSERT INTO util_test.t1 VALUES ("25 Test Basic database example"); 
INSERT INTO util_test.t1 VALUES ("26 Test Basic database example"); 
INSERT INTO util_test.t1 VALUES ("27 Test Basic database example"); 
INSERT INTO util_test.t2 VALUES ("31 Test Basic database example"); 
INSERT INTO util_test.t2 VALUES ("32 Test Basic database example"); 
INSERT INTO util_test.t2 VALUES ("33 Test Basic database example"); 

