#!/usr/bin/python

"""
==========
mysql-find
==========

---------------------------------------------------------------------
Search for processes on a MySQL server using a find(1)-like interface
---------------------------------------------------------------------


SYNOPSIS
========

  mysql-proc --user=mats --kill mats@localhost:3310

DESCRIPTION
===========

This utility can be used to easily search the process table of one or
more servers and perform actions on the processes.

"""

import optparse, mysql

# Parse options

parser = optparse.OptionParser()
parser.add_option("--match-name", dest="match_name",
                  help="Match USER", metavar="USER")
parser.add_option("--user", dest="user",
                  help="Match the user column of the PROCESSLIST table")
(options, args) = parser.parse_args()

# Construct execution object
command = mysql.commands.proc(options)

# Execute command, which return a list of tuples representing the rows
rows = command.execute(args)

# Print a nice output
theFormat = "%4s %-10s %-10s %-10s %-6s %8s %-10s %s" 
print theFormat % ('ID','USER','HOST','DB','COMMAND','TIME','STATE','INFO')
for row in rows:
    print theFormat % row
    




