#!/bin/sh

# Copyright (c) 2014, Oracle and/or its affiliates. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

# postrm script for mysql-utilities

echo "postrm script for mysql-utilities"
for PYVER in $(pyversions -i)
do
	echo "found"$PYVER
	PYDIST=`$PYVER -c "from distutils.sysconfig import get_python_lib; print (get_python_lib())"`
	echo $PYDIST
	MYSQLINIT="/mysql/__init__.py"
	if [ -d $PYDIST"/mysql" ];
	then
		SUBPKGS=`ls --ignore=*.pyc --ignore=*.pyo -m $PYDIST/mysql`
		if [ "$SUBPKGS" = "__init__.py" ];
		then
			rm $PYDIST$MYSQLINIT
			rmdir $PYDIST/mysql/
		fi
	else
		echo "not found /mysql"
	fi
done

PYSHARED="/usr/share/pyshared"
# Try to remove the MySQL top package mysql/
SUBPKGS=`ls --ignore=*.pyc --ignore=*.pyo -m $PYSHARED/mysql`
if [ "$SUBPKGS" = "__init__.py" ];
then
	echo "$PYSHARED/mysql/__init__.py*"
    rm $PYSHARED/mysql/__init__.py*
    # This should not fail, but show error if any
    rmdir $PYSHARED/mysql/
fi

#DEBHELPER#

exit 0
