#!/bin/sh -e

# Copyright (c) 2014, Oracle and/or its affiliates. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

#DEBHELPER#
# postinst script for mysql-utilities

echo "postinst script for mysql-utilities"
PYVERS=`pyversions -i`

echo $PYVERS
for PYVER in $(pyversions -i)
do
	echo "found"
	echo $PYVER
	PYSHARED="/usr/share/pyshared"
	PYDIST=`$PYVER -c "from distutils.sysconfig import get_python_lib; print (get_python_lib())"`
	echo $PYDIST
	MYSQLINIT="/mysql/__init__.py"
	if [ -d $PYSHARED/mysql ];
	then	
		if [ ! -f $PYSHARED$MYSQLINIT ];
		then
			#ls $PYSHARED$MYSQLINIT
			touch $PYSHARED$MYSQLINIT
			ls $PYSHARED$MYSQLINIT -l
		fi
		if [ -d $PYDIST/mysql ];
		then	
			if [ ! -f $PYDIST$MYSQLINIT ];
			then
				#ls $PYDIST
				ln -sf $PYSHARED$MYSQLINIT $PYDIST$MYSQLINIT
				ls $PYDIST/mysql -l
			fi
		else
			echo "WARNING: $PYDIST/mysql not found."
		fi
	else
		# we should not reach this point.
		echo "ERROR: $PYSHARED/mysql not found, nothing to do."
	fi
done

PYSHAREMYSQL="/usr/share/pyshared/mysql"

exit 0
